### ISSUE TITLE
nová objednávka - propisování firmy a více položek

### ISSUE THREAD

**Issue by objednavky** [objednavky/objednavky#15]
U nové objednávky   třetí a další položky se bude propisovat firma z předchozí položky (ne z první)

**Comment by grafickepracecom** [comment]
navrhuji:
- udělat objednávku jako editovatelnou tabulku s možností doplňovat řádky, nebo alespoň pod hlavičkou zveřejňovat řádky, které už jsem zadal (abych omylem nezadal 2x tu samou věc)
- ukládat řádky objednávky do stavu "připraveno k objednání", odeslat objednávku do schválení až po kompletním zadání
- na úvodní stránce bych měl vidět rozpracované objednávky s možností jejich smazání nebo dokončení a odeslání
- tlačítka "Přidat další položku" a "Hotovo" hned vedle sebe jsou matoucí, už se mi několikrát stalo, že jsem stiskl to první a chtěl stisknout druhé, doladit
- doplnit text o přesné částce na "(zaokrouhlená na celé Kč nahoru)"

**Comment by grafickepracecom** [comment]
odsunuto na prosinec

**Comment by grafickepracecom** [comment]
Funkcionalita zadávání nové objednávky přepracována, nyní se až do uložení drží celá jen v session, do DB jde až po uložení. Další případné požadavky a připomínky dávat do nového issue.
