### ISSUE TITLE
napojení na Money S4

### ISSUE THREAD

**Issue by objednavky** [objednavky/objednavky#18]
jako první potřebujeme udělat analýzu toho jak a co vlastně napojit, včetně rozebrání scénářů (více dokladů na jednu objednávku, jeden doklad na více objednávek, doklad s více položkami atd.)

**Comment by grafickepracecom** [comment]
hotovo, data z deníku se sehrávají každé ráno (okolo 4:00h) do databáze money_migrace tabulky denik_import. Tabulka se při exportu kompletně smaže a znovu naplní.
