### ISSUE TITLE
Chyba na titulní stránce v přehledu

### ISSUE THREAD

**Issue by objednavky** [objednavky/objednavky#2]
Schválená objednávka se zobrazí jako objednávka ke schválení  - může to být matoucí.
Buď změnit popis nebo nastavit jinak. Kosmetická vada, nemá vliv na schvalování

**Comment by objednavky** [comment]
- [ ] Nutné opravit ve verzi 2

**Comment by objednavky** [comment]
Zkouším tu nastavit, že bych to chtěla opravit do verze 2, ale nenapadá mne jak.
Ráda bych měla úkoly rozdělené podle priorit - např. tohle beru jako prioritu 1 .
Nedá se tu rozdělovat issues do kategorií? Zatím jsem přišla jen na labels. (což není špatné, ale nestačí to)

**Comment by grafickepracecom** [comment]
doplnil jsem milestones = milníky, které slouží k zařazení do verze. Labels jsem předělal na prioritizaci (něco může být P3=nízká, ale chceme to udělat do V1, nebo obráceně) a na zařazení jestli jde o novinku, úpravu nebo chybu

**Comment by grafickepracecom** [comment]
úvodní obrazovka byla přepracována, issue už není relevantní
