### ISSUE TITLE
Diskuze o funcionalitě

### ISSUE THREAD

**Issue by objednavky** [objednavky/objednavky#21]
Rozhodnout o

- [x] Jak pracovat v případě, že se zamítne jen část objednávky - ujasnit si, že to platí

- [x] Jak pracovat v případě, že má rozpočet i příjem (např. plavání, případně hudební Pavly)

- [x] Vymyslet, jestli jsou potřeba záporné objednávky (zatím mi myslím, že spíš ne)

**Comment by grafickepracecom** [comment]
Objednávka by měla mít smysl jako celek, jako taková je podle mě buď celá schválená, nebo celá zamítnutá. Měli bychom sledovat stav celé objednávky (nejen položky). Znamená to znovu vymyslet a přepsat celé schvalovací workflow.

**Comment by grafickepracecom** [comment]
Příjmy - viz dnešní diskuze na FS. Rozpočet může mít příjmy, pak je skupina může použít v rámci rozpočtu na co potřebuje a odpovídá to zaměření rozpočtu. Otázka k dořešení je, jak takový příjem poznat v účetnictví a zda stačí, aby se objevil příjem v účetním deníku, nebo zda na něj má existovat objednávka.

**Comment by grafickepracecom** [comment]
Záporná objednávka - myslím, že využití by mít mohla, např. dobropis vráceného zboží. Smysl to má ve chvíli, kdy chceme, aby správce takový dokument schvaloval, což by u dobropisu z reklamace asi měl. Toto je ještě k rozmyšlení, souvisí to do určité míry s příjmy rozpočtu.

**Comment by grafickepracecom** [comment]
odsunuto na prosinec

**Comment by grafickepracecom** [comment]
zamítnutá část objednávky zůstane jako možnost, prostě se ignoruje
příjmy budeme řešit až z účetnictví (mínusy u 5xx, plusy u 6xx) v některé z dalších verzí
zápornou objednávku tím pádem neřešíme, i nadále nebude možné ji zadat
