### ISSUE TITLE
Umožnit vybírat účtárně po celých objednávkách 

### ISSUE THREAD

**Issue by objednavky** [objednavky/objednavky#7]
Hlídat, zda jsou potvrzené všechny položky. Zamítnuté se nepočítají.

**Comment by objednavky** [comment]
Objednávku zobrazit ve schválených, jen pokud nemá žádnou položku, která čeká na schválení nebo ověření.
Zobrazovat i počet položek.

**Comment by grafickepracecom** [comment]
Objednávka se zamítnutými položkami by neměla být schválena. Souvisí s #21
