### ISSUE TITLE
zopakování staré objednávky

### ISSUE THREAD

**Issue by objednavky** [objednavky/objednavky#9]

**Comment by objednavky** [comment]
Možnost vzít smazanou/zamítnutou objednávku, editovat ji a poslat znovu do schvalování

**Comment by grafickepracecom** [comment]
Nyní už má účtárna a administrátoři možnost toto udělat. Pro ostatní je funkcionalita také připravena, mohou editovat jen vlastní objednávky, zatím nebyla uvolněna, čekám na otestování v praxi (položka menu se zatím ukazuje jen rolím "finance" a "admin").
